insert into Movies (Id, Title, Director, Year, Studio) values (1, 'Dream Team 1935', 'Lari Barton', 2012, 'Yost Inc');
insert into Movies (Id, Title, Director, Year, Studio) values (2, 'Kiss of the Dragon', 'Sayres Gonsalvez', 1992, 'Keeling, Steuber and Heathcote');
insert into Movies (Id, Title, Director, Year, Studio) values (3, 'La vérité si je mens !', 'Alonzo Pound', 1994, 'Bayer Group');
insert into Movies (Id, Title, Director, Year, Studio) values (4, 'Glass Shield, The', 'Gwyn Bartoletti', 2002, 'Metz, Gibson and Breitenberg');
insert into Movies (Id, Title, Director, Year, Studio) values (5, 'Mysterious X, The (Sealed Orders) (Det hemmelighedsfulde X)', 'Barron Wayne', 1992, 'Yost-Cremin');
insert into Movies (Id, Title, Director, Year, Studio) values (6, 'Come Back to Me', 'Henri Speariett', 2003, 'Hayes Group');
insert into Movies (Id, Title, Director, Year, Studio) values (7, 'Highball', 'Constantine Raven', 1989, 'Dietrich, Zulauf and Wolf');
insert into Movies (Id, Title, Director, Year, Studio) values (8, 'Tavarataivas', 'Eadith Drivers', 2006, 'Fisher-Hahn');
insert into Movies (Id, Title, Director, Year, Studio) values (9, 'Garlic Is As Good As Ten Mothers', 'Ashly Undy', 2000, 'Keeling-Terry');
insert into Movies (Id, Title, Director, Year, Studio) values (10, 'Remember the Night', 'Pooh Pulham', 1989, 'Hauck Group');
insert into Movies (Id, Title, Director, Year, Studio) values (11, 'America''s Most Haunted Inns', 'Beale Heffron', 2000, 'Rolfson, Deckow and Mante');
insert into Movies (Id, Title, Director, Year, Studio) values (12, 'Pink Ribbons, Inc.', 'Sidnee Lipson', 1993, 'Jacobson and Sons');
insert into Movies (Id, Title, Director, Year, Studio) values (13, 'High Tension (Haute tension) (Switchblade Romance)', 'Judi Carleman', 2001, 'Runolfsdottir, Morissette and Kuvalis');
insert into Movies (Id, Title, Director, Year, Studio) values (14, 'Herman''s House', 'Helaine Prys', 1999, 'Kuvalis-Casper');
insert into Movies (Id, Title, Director, Year, Studio) values (15, 'Main Hoon Na', 'Danit Torrie', 1999, 'Mohr LLC');
insert into Movies (Id, Title, Director, Year, Studio) values (16, 'It Rains in My Village (Bice skoro propast sveta)', 'Quincy Skowcraft', 1989, 'Hintz-Hoppe');
insert into Movies (Id, Title, Director, Year, Studio) values (17, 'Smiles of a Summer Night (Sommarnattens leende)', 'Burt Piddlehinton', 1997, 'Langosh, Hodkiewicz and Maggio');
insert into Movies (Id, Title, Director, Year, Studio) values (18, 'Little Lord Fauntleroy', 'Simon Stollery', 2010, 'Gulgowski-Moore');
insert into Movies (Id, Title, Director, Year, Studio) values (19, 'Valentine''s Day', 'Emmie Grimoldby', 2009, 'Runolfsdottir, DuBuque and Marquardt');
insert into Movies (Id, Title, Director, Year, Studio) values (20, 'Brief Interviews with Hideous Men', 'Ami Lawton', 2001, 'Crist, Stracke and Schuppe');
insert into Movies (Id, Title, Director, Year, Studio) values (21, 'Better Things', 'Maxy Gockeler', 1995, 'Beatty-Rice');
insert into Movies (Id, Title, Director, Year, Studio) values (22, 'Impromptu', 'Loella Mattingley', 1981, 'Hane, Lehner and Gutmann');
insert into Movies (Id, Title, Director, Year, Studio) values (23, 'Angel of Death', 'Olia Joyson', 1999, 'King-Zieme');
insert into Movies (Id, Title, Director, Year, Studio) values (24, 'Brief Encounter', 'Denna Matijevic', 2009, 'Mayer and Sons');
insert into Movies (Id, Title, Director, Year, Studio) values (25, 'Battle for the Planet of the Apes', 'Roley Fann', 2008, 'Rau-Sawayn');
insert into Movies (Id, Title, Director, Year, Studio) values (26, 'Shadowzone', 'Lois Chisnell', 2000, 'Klocko and Sons');
insert into Movies (Id, Title, Director, Year, Studio) values (27, 'Donnie Brasco', 'Loreen Hollier', 2001, 'Effertz-Rau');
insert into Movies (Id, Title, Director, Year, Studio) values (28, 'Que Viva Mexico (¡Que Viva Mexico! - Da zdravstvuyet Meksika!)', 'Ingmar Gockelen', 2012, 'Hegmann Inc');
insert into Movies (Id, Title, Director, Year, Studio) values (29, 'Inside Job', 'Cindee Cabrer', 2007, 'Satterfield, Schultz and Tillman');
insert into Movies (Id, Title, Director, Year, Studio) values (30, 'My Son John', 'Cheri McTavish', 1995, 'Leffler Inc');
insert into Movies (Id, Title, Director, Year, Studio) values (31, 'Majesteit', 'Tisha Tonna', 1991, 'Ward-Ankunding');
insert into Movies (Id, Title, Director, Year, Studio) values (32, 'Hurlyburly', 'Gilbertine Twitching', 2004, 'Hirthe, Beahan and Wehner');
insert into Movies (Id, Title, Director, Year, Studio) values (33, 'Devil''s in the Details, The', 'Amos Chellam', 1993, 'Boehm Inc');
insert into Movies (Id, Title, Director, Year, Studio) values (34, 'Top Dog', 'Tades Kubas', 1995, 'Yundt LLC');
insert into Movies (Id, Title, Director, Year, Studio) values (35, 'Furry Vengeance', 'Burnaby Ardron', 2006, 'Halvorson-Berge');
insert into Movies (Id, Title, Director, Year, Studio) values (36, 'Evil Cult, The (Lord of the Wu Tang) (Yi tian tu long ji: Zhi mo jiao jiao zhu)', 'Nisse Norman', 2000, 'Walter Inc');
insert into Movies (Id, Title, Director, Year, Studio) values (37, 'Romance in Manhattan', 'Miner Badger', 1993, 'Daugherty-Hickle');
insert into Movies (Id, Title, Director, Year, Studio) values (38, 'Two Weeks in September', 'Liuka Creamer', 2012, 'Rodriguez and Sons');
insert into Movies (Id, Title, Director, Year, Studio) values (39, 'Liar''s Dice', 'Gareth O'' Mullan', 1997, 'Stark-Barrows');
insert into Movies (Id, Title, Director, Year, Studio) values (40, 'Quiet Ones, The', 'David Blamire', 2010, 'Fay Inc');
insert into Movies (Id, Title, Director, Year, Studio) values (41, 'Castle of Purity (El castillo de la pureza)', 'Camellia Simms', 1998, 'Hammes, Bauch and Dickinson');
insert into Movies (Id, Title, Director, Year, Studio) values (42, 'World''s Greatest Dad', 'Payton Bennellick', 2008, 'Goyette LLC');
insert into Movies (Id, Title, Director, Year, Studio) values (43, 'There''s Something Wrong with Aunt Diane', 'Rozella Liversidge', 1999, 'Bashirian, Lubowitz and Gerlach');
insert into Movies (Id, Title, Director, Year, Studio) values (44, 'Others, The', 'Karen Harle', 2009, 'Wunsch-Hilpert');
insert into Movies (Id, Title, Director, Year, Studio) values (45, 'Point Blank', 'Wildon Stuchberry', 2013, 'Bogan-Ziemann');
insert into Movies (Id, Title, Director, Year, Studio) values (46, 'Ingmar Bergman Makes a Movie (Ingmar Bergman gör en film)', 'Pris Huggill', 2003, 'Hauck and Sons');
insert into Movies (Id, Title, Director, Year, Studio) values (47, 'Love Simple', 'Karina Highman', 1997, 'Schmeler-Hettinger');
insert into Movies (Id, Title, Director, Year, Studio) values (48, 'Bloodstone: Subspecies II', 'Barry Huff', 2009, 'Mueller Inc');
insert into Movies (Id, Title, Director, Year, Studio) values (49, 'Van Helsing', 'Aarika Fairbrother', 2009, 'Moore, Kilback and Little');
insert into Movies (Id, Title, Director, Year, Studio) values (50, 'Stick', 'Lazar Raubenheimers', 2007, 'Cormier Inc');
insert into Movies (Id, Title, Director, Year, Studio) values (51, 'Strangers, The', 'Alfonso Ashelford', 2000, 'Balistreri LLC');
insert into Movies (Id, Title, Director, Year, Studio) values (52, 'Pan''s Labyrinth (Laberinto del fauno, El)', 'Branden Thorneloe', 2003, 'Leuschke-Hettinger');
insert into Movies (Id, Title, Director, Year, Studio) values (53, 'This So-Called Disaster', 'Jerrylee Morena', 2001, 'Schultz-Smitham');
insert into Movies (Id, Title, Director, Year, Studio) values (54, 'Red Balloon, The (Ballon rouge, Le)', 'Joletta Lusk', 1999, 'Lakin LLC');
insert into Movies (Id, Title, Director, Year, Studio) values (55, 'Flying Down to Rio', 'Tracy Oehm', 2010, 'Mante and Sons');
insert into Movies (Id, Title, Director, Year, Studio) values (56, 'The Bronze', 'Deina Cocher', 1989, 'Huels, Schmitt and Kutch');
insert into Movies (Id, Title, Director, Year, Studio) values (57, 'Flaw, The', 'Waverly Beers', 1994, 'Runte Group');
insert into Movies (Id, Title, Director, Year, Studio) values (58, 'High Crimes', 'Brittany Kettlestringe', 1987, 'Grady and Sons');
insert into Movies (Id, Title, Director, Year, Studio) values (59, 'Hunchback of Notre Dame, The', 'Baudoin Zannetti', 2002, 'Deckow-Jaskolski');
insert into Movies (Id, Title, Director, Year, Studio) values (60, 'Secret', 'Lindie Bullard', 2011, 'Willms-Steuber');
